spring:
  application:
    name: spring-cloud-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: toFeign
        uri: lb://spring-cloud-eureka-feign-client
        predicates:
          - Path=/get-greeting
          - Method=GET
      - id: toEurekaClient
        uri: lb://spring-cloud-eureka-client
        predicates:
          - Path=/greeting
          - Method=GET
      - id: toSleuthTest
        uri: lb://sleuth-test
        predicates:
          - Path=/sleuthGreeting
          - Method=GET
server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
